[package]
name = "kdtrees"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"

[profile.release]
opt-level = 3
lto = "fat"        # More aggressive link-time optimization
codegen-units = 1  # Better optimizations, but slower compile
panic = "abort"    # Removes unwinding, reduces binary size


